// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZA3LOiLZcU_mstwxDtLOfqH-fMYZAow',
    appId: '1:195927192535:web:e7db16e584906ad8d49192',
    messagingSenderId: '195927192535',
    projectId: 'tasklist-b6fce',
    authDomain: 'tasklist-b6fce.firebaseapp.com',
    databaseURL: 'https://tasklist-b6fce-default-rtdb.firebaseio.com',
    storageBucket: 'tasklist-b6fce.firebasestorage.app',
    measurementId: 'G-7RJYZHRJX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXge4CLMAbP35i5FB6YUGsS6WskvXVyMg',
    appId: '1:195927192535:android:5136b40f05d98bb2d49192',
    messagingSenderId: '195927192535',
    projectId: 'tasklist-b6fce',
    databaseURL: 'https://tasklist-b6fce-default-rtdb.firebaseio.com',
    storageBucket: 'tasklist-b6fce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpkf9aWgkGFIg4lKHXsh6vKwJlDeTzXz0',
    appId: '1:195927192535:ios:56130a144b9ba285d49192',
    messagingSenderId: '195927192535',
    projectId: 'tasklist-b6fce',
    databaseURL: 'https://tasklist-b6fce-default-rtdb.firebaseio.com',
    storageBucket: 'tasklist-b6fce.firebasestorage.app',
    iosBundleId: 'com.example.taskList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpkf9aWgkGFIg4lKHXsh6vKwJlDeTzXz0',
    appId: '1:195927192535:ios:56130a144b9ba285d49192',
    messagingSenderId: '195927192535',
    projectId: 'tasklist-b6fce',
    databaseURL: 'https://tasklist-b6fce-default-rtdb.firebaseio.com',
    storageBucket: 'tasklist-b6fce.firebasestorage.app',
    iosBundleId: 'com.example.taskList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtZA3LOiLZcU_mstwxDtLOfqH-fMYZAow',
    appId: '1:195927192535:web:4864f22364340b74d49192',
    messagingSenderId: '195927192535',
    projectId: 'tasklist-b6fce',
    authDomain: 'tasklist-b6fce.firebaseapp.com',
    databaseURL: 'https://tasklist-b6fce-default-rtdb.firebaseio.com',
    storageBucket: 'tasklist-b6fce.firebasestorage.app',
    measurementId: 'G-D3F3VHSN17',
  );
}
